"""add is_verified and verification_sent_at to users

Revision ID: 401e38f92e10
Revises: 5962abdb34b2
Create Date: 2026-09-12 15:49:58.972493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401e38f92e10'
down_revision: Union[str, Sequence[str], None] = '5962abdb34b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('verification_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_sent_at')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
